### ISSUE TITLE
Shelly 2 Hue Script - Adoption to Hue Groups & usage of switch instead of button

### ISSUE THREAD

**Issue by 2slow4u** [shelly-tools/shelly-script-examples#1]
Hi,
I saw your script to control a Hue lightbulb via Shelly today.

Unfortunately it did not quite match my setup, as I need to toggle a group of Hue Lightbulbs and I'm using a switch instead of a button. Therefore I used your script as a basis, but adopted it to fit my setup.

In case you'd like to take a look and maybe use this also in some of your setup, please feel free to do so:
https://github.com/2slow4u/Scripts/blob/main/Shelly/Shelly2Hue_Switch.js

Take care!
T

**Comment by mf-1** [comment]
Have a look into this script.

https://github.com/mf-1/shelly-script-examples/blob/main/shelly-plus-2pm_switch_controller_hue-relay.js

**Comment by eurich** [comment]
@2slow4u @mf-1 great to see others working on scripts, too :) I'd be happy to add your scripts, feel free to send a Pull request.

**Comment by mf-1** [comment]
> I'd be happy to add your scripts, feel free to send a Pull request.

@eurich  Already done some days ago ... 

![image](https://user-images.githubusercontent.com/1529283/161828655-7c152a29-1875-4935-a458-33e182826bc8.png)

**Comment by eurich** [comment]
thank you @mf-1 and sorry for the delay..
