### ISSUE TITLE
central_shutter_switch help

### ISSUE THREAD

**Issue by davide5681** [shelly-tools/shelly-script-examples#11]
hello, i copied this script in my shelly i4. I changed the ip of the master (in my case this shelly i4) which controls 10 shelly 2.5 roller shutters.
I changed the ip of the roller shutters. but when I give input signal 1 it gives me open value but then it gives me code errors-. could you help me?

**Comment by eurich** [comment]
it's not possible to control more than 5 devices because the number of Shelly.Calls is limited to 5.
Master is not the IP from the Shelly I4 but the first shutter which is used to determine the position.

**Comment by davide5681** [comment]
Ok thank you very much

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
