### ISSUE TITLE
dim=cycle command not working

### ISSUE THREAD

**Issue by Hansontech190** [shelly-tools/shelly-script-examples#15]
emulate_multiple_dimmers.js 

Using the above code with a Dimmer 2 works well except for hold to dim and cycle.  This is not working to cycle through dim to bright.  If I alter the code to dim=up or down then this works but cycle is not working.

**Comment by Hansontech190** [comment]
Shelly technical have confirmed that dim=cycle won’t work with the new Shelly GEN2 units due to changes in chipset. 
If you can modify the script to work with the newer Shelly devices that would be great.

**Comment by eurich** [comment]
The script was updated 4 days ago (2 days before your bug report) and dim=cycle replaced with a somewhat emulated version.

https://github.com/shelly-tools/shelly-script-examples/blob/main/emulate_multiple_dimmers.js
