### ISSUE TITLE
emulate_dimmer_button.js im i4

### ISSUE THREAD

**Issue by MarkusSorger** [shelly-tools/shelly-script-examples#5]
Moin,

sehr schöne Lösung, um Dimmer fernzusteuern. Allerdings stolpere ich an einer Stelle: wenn ich das Skript in einen i4 lade, ist mir nicht ersichtlich, wie ich bestimmen kann, auf welchem Eingang das Skript liegen soll. Es wirkt immer auf Eingang 0. Wie lege ich das Skrip auf einen anderen Eingang als den ersten ?

Hintergrund: ich würde gerne die Zweitastenbedienung des Dimmers emulieren. Dazu müsste ich ja nur beim dim - Befehl das "circle" in "up" oder "down" ändern und dann diese beiden unterschiedlichen Versionen unterschiedlichen Eingängen des i4 zuordnen. Wie ich das machen kann, erschließt sich mir aber leider nicht. Magst Du mir das bitte erklären ?

Ganz herzlichen Dank und viele Grüße

   Markus

**Comment by eurich** [comment]
the input has to be defined in line 14, I've updated the script with a related comment.

**Comment by Mabidmon** [comment]
Hey,

ich habe irgendwie das gleiche Problem - in der Zeile 12 kann man die IP und den Button eintragen aber egal welche Zahl ich beim Button eintrage, es wird immer Button 0 genommen. Verstehe ich etwas nicht?
<img width="371" alt="Screenshot 2024-03-21 175429" src="https://github.com/shelly-tools/shelly-script-examples/assets/162759598/f0c7f840-9f75-43d9-9e9d-29059ad90119">
