### ISSUE TITLE
hue_toggle_switch.js mehrere Lampen

### ISSUE THREAD

**Issue by Kai9555** [shelly-tools/shelly-script-examples#7]
Hi,

ist es möglich über hue_toggle_switch.js auch mehrere Lampen anzusprechen. Ich habe einen Treppenaufgang mit 5 Hue Lampen, die über einen Schalter angesprochen werden sollten.

Vielen Dank für die Mühe.

VG Kai

**Comment by Nettrick** [comment]
Hi,
gibt es hirzu schon eine Lösung, ich habe das selbe Problem, leider kann ich nur 3 Scripte auf meinem Shelly 4 laufen lassen.
Danke

**Comment by Nettrick** [comment]
Hi, ich habe nochmal etwas experimentiert, ich habe im Skript einfach diesen Eintrag mehrfach kopiert und die ID manuell eingetragen:
    Shelly.call(
        "http.request", {
        method: "PUT",
        url: 'http://' + CONFIG.ip + '/api/' + CONFIG.user + '/lights/' + "z.B. 4" + '/state',
        body: b
    },
        function (r, e, m) {
        },
        null
    );

**Comment by Kai9555** [comment]
> Hi, ich habe nochmal etwas experimentiert, ich habe im Skript einfach diesen Eintrag mehrfach kopiert und die ID manuell eingetragen:
> Shelly.call(
> "http.request", {
> method: "PUT",
> url: 'http://' + CONFIG.ip + '/api/' + CONFIG.user + '/lights/' + "z.B. 4" + '/state',
> body: b
> },
> function (r, e, m) {
> },
> null
> );

Also hast du eine Lösung gefunden?

Könntest du das gesamte Script einmal posten? Dankeschön und VG

**Comment by eurich** [comment]
hiermit lässt sich eine Gruppe via Schalter an/aus schalten:
https://github.com/shelly-tools/shelly-script-examples/blob/main/hue_switch_control_group.js

**Comment by eurich** [comment]
hier jetzt mal 4 Beispiele, wie man die Lampen steuern kann.. 

mit einem Taster eine Lampe an/aus schalten.
https://github.com/shelly-tools/shelly-script-examples/blob/main/hue_button_control_light.js

mit einem Taster eine Gruppe an/aus schalten.
https://github.com/shelly-tools/shelly-script-examples/blob/main/hue_button_control_group.js


mit einem Schalter eine Lampe an/aus schalten.
https://github.com/shelly-tools/shelly-script-examples/blob/main/hue_switch_control_light.js

mit einem Schalter eine Gruppe an/aus schalten.
https://github.com/shelly-tools/shelly-script-examples/blob/main/hue_switch_control_group.js

**Comment by Kai9555** [comment]
> hier jetzt mal 4 Beispiele, wie man die Lampen steuern kann..
> 
> mit einem Taster eine Lampe an/aus schalten. https://github.com/shelly-tools/shelly-script-examples/blob/main/hue_button_control_light.js
> 
> mit einem Taster eine Gruppe an/aus schalten. https://github.com/shelly-tools/shelly-script-examples/blob/main/hue_button_control_group.js
> 
> mit einem Schalter eine Lampe an/aus schalten. https://github.com/shelly-tools/shelly-script-examples/blob/main/hue_switch_control_light.js
> 
> mit einem Schalter eine Gruppe an/aus schalten. https://github.com/shelly-tools/shelly-script-examples/blob/main/hue_switch_control_group.js

Hallo und vielen Dank für deine Mühe. Ich habe mich schon gefreut meine Gruppen einzurichten, leider stimmt etwas nicht. Ich habe das Script für "Schalter über eine Gruppe steuern" genommen, die IP, den user und Group sowie input1 eingetragen. Wenn ich das Script starte, dann gehen die Lampen der Gruppe einfach immer an und aus, ohne dass ich etwas schalte. Hast du eine Idee?
